[serve]
addresses = ["127.0.0.1"]

port = 8000

# Proxy /api requests to our backend server.
[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/api/"

# Add these lines to include highlight.js assets
[[head]]
html = """
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
"""