//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::execution_results::Entity as ExecutionResults;
pub use super::submissions::Entity as Submissions;
pub use super::test_cases::Entity as TestCases;
