[package]
name = "heurs-back"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
heurs-core = { path = "../core" }
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
